### ISSUE TITLE
Preview Render Problems

### ISSUE THREAD

**Issue by Copy33** [Quivr/Android-Week-View#114]
Rendering isn't working in the preview on the latest Android Studio:

java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed   at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)   at android.graphics.Canvas.clipRect(Canvas.java:918)   at com.alamkanak.weekview.WeekView.drawHeaderRowAndEvents(WeekView.java:84

**Comment by marunjar** [comment]
should work again with PR #124 (tested with android studio 3.5.3)
